import joblib
import os
import xgboost as xgb
import sklearn

MODEL_PATH = "models/xgboost_phishing_model.joblib"
SCALER_PATH = "models/phishing_scaler.joblib"

if os.path.exists(MODEL_PATH) and os.path.exists(SCALER_PATH):
    print("Loading existing models...")
    model = joblib.load(MODEL_PATH)
    scaler = joblib.load(SCALER_PATH)
    
    # Re-save to normalize versions if they were generated by a different version
    print(f"Re-saving models with current versions (XGBoost: {xgb.__version__}, Sklearn: {sklearn.__version__})...")
    joblib.dump(model, MODEL_PATH)
    joblib.dump(scaler, SCALER_PATH)
    print("Successfully re-saved models.")
else:
    print("Models not found. Please ensure 'models/' folder is present.")
